### ISSUE TITLE
Megamenu causes problems when switching from mobile to desktop

### ISSUE THREAD

**Issue by G-dogger** [marioloncarek/megamenu-js#12]
If you have your browser window shrunk down below the breakpoint in mobile mode and you open a Megamenu (submenu). Then if you resize your browser to desktop view, the one sub-menu stays open. You can't clear it our unless you refresh the page.

**Comment by marioloncarek** [comment]
Its a know issue, its fixed in v2. You just need to close everything on windows resize. You can see example from v2 starting on line 86. 

https://github.com/marioloncarek/megamenu-js/blob/v2/src/js/megamenu.js

**Comment by G-dogger** [comment]
Oh great, I will check this out tomorrow. Thank you so much, and great job!

**Comment by G-dogger** [comment]
Sorry, way too confusing for me. Does your v2 require all new html, css, and js files? I can't get it to work. Do you have a working demo of v2 online, so I can see it work in action?

**Comment by G-dogger** [comment]
If not is there a way to just modify the existing js file to fix the resize bug?

**Comment by marioloncarek** [comment]
it requires everything new, i just gave you a snippet how to make it work from v2. Download the repo for demo. Yes there is read my first response where you can see example how i fixed it on v2

**Comment by G-dogger** [comment]
Okay, I replace all files, I forgot the jquery.min. Now it works properly, plus I see you added the new hamburger transition to an X feature. Nice. Thank you so much!

**Comment by piedicosta** [comment]
Hello marioloncarek, I have the same issue but I don't understand how to fix it.
Where can I find the v2 of this Megamenu?
Thank you for your kind support and congratulation for this beautiful menu!
Filippo

**Comment by marioloncarek** [comment]
https://github.com/marioloncarek/megamenu-js - thats the main page of this repo, you will have to find a dropdown menu which says "Branch: master" . From that menu just choose v2 and then you will be switched to that branch.

**Comment by piedicosta** [comment]
Thank you Marco, I will check it tomorrow!

Untitled Document

*Filippo Bracci* *
*/Piè di Costa /
www.piedicosta.com <http://www.piedicosta.com>
============================

Il 28/12/16 11:02, Mario Loncarek ha scritto:

**Comment by piedicosta** [comment]
Hello Mario and Happy new year!

I have installed the Megamenu V2 and I found awesome!

In particular I have not installed all the file inside the folder 
"megamenu-js-2" but only the ones called by index.html

However I wonder if all instructions inside style.css are necessary 
because when I install on my website www.visitmontaione.com/jnuovo it 
seems it goes in conflict with some other instructions inside my other 
.css files too, in particular with "body", "html", "a", etc... and make 
the menu NOT working properly.
Untitled Document

**Do you have some tips to solve this issue?

Thank you in advance for your kind help!

Filippo



Il 28/12/16 11:02, Mario Loncarek ha scritto:
